### ISSUE TITLE
ERROR  Cannot restart nuxt:  The "name" argument must be specified   

### ISSUE THREAD

**Issue by angi-** [tresko/nuxt-module-feed#31]
I installed `nuxt-module-feed` and the moment I add it to nuxt.config.ts I get the error:

```
ℹ nuxt.config.ts updated. Restarting nuxt...

 ERROR  Cannot restart nuxt:  The "name" argument must be specified

  at new NodeError (node:internal/errors:399:5)
  at Performance.mark (node:internal/perf/performance:125:13)
  at normalizedModule (node_modules/nuxt-module-feed/node_modules/@nuxt/kit/dist/index.mjs:168:30)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:452:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2616:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6824:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6737:10)
```

My package.json looks like:

```
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/content": "^2.5.2",
    "@types/node": "^18",
    "@types/rss": "^0.0.30",
    "nuxt": "^3.4.1",
    "nuxt-module-feed": "^1.0.3"
  },
  "dependencies": {
    "rss": "^1.2.2"
  }
}
```

**Comment by tresko** [comment]
Are you using node 19?

**Comment by angi-** [comment]
> Are you using node 19?

Yes, v19.9.0

**Comment by tresko** [comment]
Try to downgrade node to v18.

**Comment by Otto-J** [comment]
same issue. node v20.5.1
